services:
  - type: web
    name: n8n-free-service
    env: docker
    plan: free
    # Uses the official docker image from n8n
    imageRepo: docker.n8n.io/n8nio/n8n
    # Sets the port that n8n operates on internally
    port: 5678
    envVars:
      # Database Configuration (Supabase)
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        sync: false
      - key: DB_POSTGRESDB_PORT
        value: "5432"
      - key: DB_POSTGRESDB_DATABASE
        value: postgres
      - key: DB_POSTGRESDB_USER
        value: postgres
      - key: DB_POSTGRESDB_PASSWORD
        sync: false

      # n8n General Settings
      - key: N8N_HOST
        sync: false # Set this to your generated format: name.onrender.com
      - key: WEBHOOK_URL
        sync: false # Set this to: https://onrender.com
      
      # Encryption Key for your credentials inside n8n
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
